name 'appcanary'
maintainer 'Michael MacLeod'
maintainer_email 'hello@appcanary.com'
license 'GPLv3'
description 'Installs/Configures appcanary'
long_description 'Installs/Configures appcanary'
source_url       'https://github.com/appcanary/chef-appcanary'
version '0.1.8'

depends 'packagecloud', '~> 0.0.19'
